from django.conf.urls import patterns, include, url
from django.contrib.auth.decorators import login_required
from .views import *
from apps.store.views import *
from apps.account.views import *
from apps.blog.views import *

urlpatterns = patterns('',
	url(r'^$', MyFarm.as_view(),name='mi_agro'),
	url(r'^preguntas$', ProductCommentsListView.as_view(), name='product_comment'),
    url(r'^registrar-granja', RegisterFarm.as_view(), name='register_farm'),
	url(r'^buzon-sugerencias$', MailboxList.as_view(), name='mailbox'),
	url(r'^buzon-sugerencias/(?P<pk>\d+)$', MailboxView.as_view(), name='mailbox_response'),
	url(r'^agro-blog$', BlogList.as_view(), name='blog'),
	url(r'^blog/nueva$', BlogAddView.as_view(), name='blog_add'),
	url(r'^blog/ver/(?P<pk>\d+)/$', BlogView.as_view(), name='blog_view'),
	url(r'^blog/editar/(?P<pk>\d+)/$', BlogUpdateView.as_view(), name='blog_edit'),
	url(r'^formas-pago$', PaymentsList.as_view(), name='payments'),
	url(r'^opiniones$', UserFeedbackView.as_view(), name='feedback'),
	url(r'^estadisticas$', StatisticsView.as_view(), name='statistics'),
	url(r'^formas-pago/nuevo$', PaymentFarmCreate.as_view(), name='payment_add'),
	url(r'^formas-pago/editar/(?P<pk>\d+)/$', PaymentFarmUpdate.as_view(), name='payment_update'),
	url(r'^formas-pago/borrar/(?P<pk>\d+)/$', PaymentFarmDeleteView.as_view(), name='payment_delete'),
	url(r'^opciones-envio$', ShippingOptionList.as_view(), name='shipping_options'),
	url(r'^ordenes-compra$', PurchaseOrderList.as_view(), name='purchase_orders'),
	url(r'^ordenes-compra/(?P<pk>\d+)/$', OrderSellerView.as_view(), name='order_seller'),
	url(r'^mis-compras$', MyShoppingList.as_view(), name='my_shopping'),
	url(r'^mis-compras/(?P<pk>\d+)/$', OrderBuyerView.as_view(),name='order_buyer'),
	url(r'^mis-compras/(?P<pk>\d+)/calificar$', FeedbackOrderView.as_view(),name='feedback_order'),
	url(r'^opciones-envio/nuevo$', ShippingOptionCreate.as_view(), name='shipping_option_add'),
	url(r'^opciones-envio/editar/(?P<pk>\d+)/$', ShippingOptionUpdate.as_view(), name='shipping_option_update'),
	url(r'^opciones-envio/borrar/(?P<pk>\d+)/$', ShippingOptionDeleteView.as_view(), name='shipping_option_delete'),
	url(r'^desactivar$', DeactivateFarmView.as_view(), name='deactivate_farm'),
	url(r'^activar$', ActivateFarmView.as_view(), name='activate_farm'),
    url(r'^granja-exitosa', 'apps.farm.views.farmSuccess', name='farm_success'),
    url(r'^productos', include('apps.product.urls',namespace='product_app', app_name='product')),
	url(r'^asociaciones', include('apps.groups.urls',namespace='groups_app', app_name='groups')),
	url(r'^mensajes', include('apps.message.urls',namespace='message_app', app_name='message')),
	url(r'^extras', include('apps.extras.urls',namespace='extras_app', app_name='extras')),
    url(r'^perfil$',UpdateProfileView.as_view(), name='profile'),
	url(r'^direccion-envio$',AddressView.as_view(), name='address'),
	url(r'^notificaciones$',NotificationsView.as_view(), name='notifications'),
	url(r'^mis-amigos$',MyFriendList.as_view(), name='my_friends'),
	url(r'^solicitudes$',FriendInvitationList.as_view(), name='friends_invitations'),
    url(r'^cambiar-clave$',UpdatePasswordView.as_view(), name='update_password'),
    url(r'^mi-granja$', MyFarmUpdateView.as_view(), name='my_farm'),
	url(r'^changePictureProfile','apps.farm.views.changePictureProfile'),
	url(r'^changePictureBanner','apps.farm.views.changePictureBanner'),
)
