from django.conf.urls import patterns, include, url
from .views import *
from rest_framework import routers
from apps.product.models import Product
from apps.farm.models import Farm, FarmProfile

router = routers.DefaultRouter()
router.register(r'users',UserViewSet)
router.register(r'products',ProductViewSet,base_name=Product)

urlpatterns = patterns('',
	url(r'^', include(router.urls)),
	url(r'^geofarms_countcity',GeoFarmCountCityViewSet.as_view({'get':'list'}),name='geofarms_countcity'),
	url(r'^main$',MainViewSet.as_view({'get':'list'}),name='main'),
	url(r'^banners$',BannerViewSet.as_view({'get':'list'}),name='main'),
	url(r'^geofarm/$',GeoFarmViewSet.as_view({'get':'all'}),name='geofams'),
	url(r'^status$',StatusViewSet.as_view({'get':'list'})),
	url(r'^mailbox/send$',MailboxViewSet.as_view({'get':'post'})),
	url(r'^message/send$',MessageViewSet.as_view({'get':'post'})),
	url(r'^inivitation_group/send$',InivitationGroupViewSet.as_view({'get':'post'})),
	url(r'^inivitation_friend/send$',InivitationFriendViewSet.as_view({'get':'post'})),
	url(r'^login$',LoginViewSet.as_view({'get':'post'})),
	url(r'^register$',RegisterViewSet.as_view({'get':'post'})),
	url(r'^logout$',LogoutViewSet.as_view({'get':'post'})),
	url(r'^reset_password$',ResetPasswordViewSet.as_view({'get':'post'})),
	url(r'^finish_shop$',FinishShopViewSet.as_view({'get':'post'})),
	#url(r'^login/(?P<user>[-\w]+)/$',LoginViewSet.as_view({'get':'is_auth'})),
	url(r'^geofarm/(?P<slug>[-\w]+)/$',GeoFarmViewSet.as_view({'get':'category'}),name='geofams_category'),
	url(r'^user/(?P<slug>[-\w]+)/$',UserProfileMinViewSet.as_view({'get':'min'})),
	url(r'^user/(?P<slug>[-\w]+)/shipping_address/(?P<token>[-\w]+)$',UserProfileMinViewSet.as_view({'get':'shippingAddress'})),
	url(r'^users_profiles$',UserProfileMinViewSet.as_view({'get':'list'}),name='users_profiles'),
	url(r'^users_profiles$',UserProfileMinViewSet.as_view({'get':'list'}),name='users_profiles'),
	url(r'^users_profiles/(?P<slug>[-\w]+)/$',UserProfileMinViewSet.as_view({'get':'retrieve'})),
	url(r'^users_profiles/(?P<slug>[-\w]+)/friends$',FriendsViewSet.as_view({'get':'list'})),
	url(r'^users_profiles/(?P<slug>[-\w]+)/groups$',GroupsUserViewSet.as_view({'get':'list'})),
	url(r'^users_profiles/(?P<slug>[-\w]+)/states$',StatesUserViewSet.as_view({'get':'min'})),
	url(r'^users_profiles/(?P<slug>[-\w]+)/states/(?P<pk>[-\w]+)/$',StatesUserViewSet.as_view({'get':'comments'})),
	url(r'^users_profiles/(?P<slug>[-\w]+)/states_list$',StatesUserViewSet.as_view({'get':'list'})),
	url(r'^latest_products',LatestProductViewSet.as_view({'get':'list'}),name='api_latesproducts'),
	url(r'^products_category$',CategoryListViewSet.as_view({'get':'list'})),
	url(r'^products_category/(?P<pk>[-\w]+)/$',CategoryListViewSet.as_view({'get':'retrieve'})),
	url(r'^products_category/products/(?P<pk>[-\w]+)/$',ProductsCategory.as_view({'get':'list'})),
	url(r'^search/(?P<word>[-\w]+)$',SearchViewSet.as_view({'get':'list'})),
	url(r'^all_products$',AllProductMinViewSet.as_view({'get':'list'})),
	url(r'^entries$',AgroBlogViewSet.as_view({'get':'list'})),
	url(r'^entries/category/(?P<slug>[-\w]+)$',CategoryEntriesViewSet.as_view({'get':'list'})),
	url(r'^entries/entry/(?P<slug>[-\w]+)$',AgroBlogViewSet.as_view({'get':'retrieve'})),
	url(r'^farms$',FarmsViewSet.as_view({'get':'list'})),
	url(r'^farms/(?P<slug>[-\w]+)$',FarmsViewSet.as_view({'get':'retrieve'})),
	url(r'^farms/(?P<slug>[-\w]+)/products$',ProductsFarmViewSet.as_view({'get':'list'})),
	url(r'^farms/(?P<slug>[-\w]+)/options$',BuyOptionsViewSet.as_view({'get':'list'})),
	url(r'^farms/(?P<slug>[-\w]+)/payments$',PaymentsOptionsViewSet.as_view({'get':'list'})),
	url(r'^groups$',AllGroupMinViewSet.as_view({'get':'list'})),
	url(r'^groups/(?P<slug>[-\w]+)$',AllGroupMinViewSet.as_view({'get':'retrieve'})),
	url(r'^groups/(?P<slug>[-\w]+)/members$',GroupMembersViewSet.as_view({'get':'list'})),
	url(r'^groups/(?P<slug>[-\w]+)/products$',GroupProductsViewSet.as_view({'get':'list'})),
	url(r'^geofarms_category/(?P<slug>[-\w]+)/$',GeoFarmCategory.as_view({'get':'list'}),name='geofarms_category'),
	url(r'^geofarms_all$',GeoFarmCategory.as_view({'get':'all'}),name='geofarms_all'),
	url(r'^product/(?P<slug>[-\w]+)$',ProductViewSet.as_view({'get': 'retrieve'}),name='api_product'),
	url(r'^product/(?P<product>[-\w]+)/comments$',ProductCommentsViewSet.as_view({'get': 'retrieve'})),
	url(r'^product/(?P<product>[-\w]+)/feedback$',ProductCommentsViewSet.as_view({'get': 'feedback'})),
	url(r'^status_comments/(?P<pk>.+)/$',StatusCommentsViewSet.as_view({'get': 'list'}),name='api_status_comments'),
	url(r'^group_comments/(?P<pk>.+)/$',StatusGroupCommentsViewSet.as_view({'get': 'list'}),name='api_group_comments'),
	url(r'^geo_farm/(?P<slug>[-\w]+)/$',FarmsProfileViewSet.as_view({'get': 'list'}),name='geofarms_city'),
	url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
	url(r'^smilemeter$',QuestionViewSet.as_view({'get':'list'})),
	url(r'^conversations/(?P<session_key>[-\w]+)/(?P<username>[-\w]+)$',ConversationsViewSet.as_view({'get':'list'})),
	url(r'^conversations/(?P<session_key>[-\w]+)/(?P<username>[-\w]+)/(?P<sender>[-\w]+)$',MessagesViewSet.as_view({'get':'list'})),
	url(r'^auth/', include('djoser.urls.authtoken')),
	url(r'^youtube$',YoutubeViewSet.as_view({'get':'post'})),
	#url(r'^banners$',BannerViewSet.as_view({'get':'list'}),name='banners'),
)
